// examples/destination/react/src/components/gui/groups/TextFieldGroup.tsx
/**
 * テキストフィールドのグループ
 * TextField Group GUI Component
 * @inlineLabel ラベル
 * @defaultValue テキストフィールドの初期値
 * @onChanged 入力時の変更イベント
 *
 * ※誌面上では以下のコンポーネントはそれぞれの場所に移動しています。
 * - InlineLabel コンポーネント -> `gui/parts/InlineLabel.tsx`
 * - LayoutFlexItem コンポーネント -> `layouts/LayoutFlexItem.tsx`
 * - LayoutFlex コンポーネント -> `layouts/LayoutFlex.tsx`
 */
import React from "react";

// Components
import { LayoutFlex, LayoutFlexItem } from "../../layouts";
import { InlineLabel, TextField } from "../parts/";

interface Props {
  inlineLabel?: string;
  defaultValue?: string;
  onChanged?: (res: React.BaseSyntheticEvent) => void;
}

export const TextFieldGroup = (props: Props) => {
  const { inlineLabel, defaultValue, onChanged } = props;

  return (
    <LayoutFlex>
      <LayoutFlexItem column={1}>
        <InlineLabel text={inlineLabel} />
      </LayoutFlexItem>
      <LayoutFlexItem column={2}>
        <TextField defaultValue={defaultValue} onChanged={onChanged} />
      </LayoutFlexItem>
    </LayoutFlex>
  );
};

// examples/destination/vue/src/components/gui/groups/TextFieldGroup.vue
<template>
    <LayoutFlex>
      <LayoutFlexItem :column="1">
        <InlineLabel :text="inlineLabel" />
      </LayoutFlexItem>
      <LayoutFlexItem :column="2">
        <TextField :default-value="defaultValue" :on-changed="onChanged" />
      </LayoutFlexItem>
    </LayoutFlex>
</template>

<script>
/**
 * テキストフィールドのグループ
 * TextField Group GUI Component
 * @inlineLabel ラベル
 * @defaultValue テキストフィールドの初期値
 * @onChanged 入力時の変更イベント
 */

// Components
import { LayoutFlex, LayoutFlexItem } from "@/components/layouts";
import { InlineLabel, TextField } from "@/components/gui/parts/";

export default {
    name: "TextFieldGroup",
    props: {
        inlineLabel: String,
        defaultValue: String,
        onChanged: Function
    },
    components: {
        LayoutFlex, 
        LayoutFlexItem,
        InlineLabel, 
        TextField
    }
}
</script>
