// examples/aparel-ec/vue/src/components/gui/groups/ListItemGroup.vue
<template>
  <div @click="onClicked">
    <layout :has-margin="hasBottomMargin">
      <list-thumbnail-image :image="image" />
    </layout>
    <layout :has-margin="hasBottomMargin">
      <list-title :title="title" />
    </layout>

    <slot />
  </div>
</template>

<script>
/**
 * ListItemのグループ
 * ListItemGroup GUI Group Component
 * @title リストのタイトル
 * @image 画像のURL
 */

// Components
import { Layout } from "@/components/layouts";
import { ListThumbnailImage, ListTitle } from "@/components/gui/parts/";


export default {
  name: "ListItemGroup",
  props: {
    title: String,
    image: String,
    onClicked: Function
  },
  computed: {
    hasBottomMargin() {
      return { bottom: true };
    }
  },
  components: {
    Layout,
    ListThumbnailImage, 
    ListTitle
  }
}
</script>

// examples/aparel-ec/react/src/components/gui/groups/ListItemGroup.tsx
/**
 * ListItemのグループ
 * ListItemGroup GUI Group Component
 * @title リストのタイトル
 * @image 画像のURL
 */
import React from "react";

// Components
import { Layout } from "../../layouts";
import { ListThumbnailImage, ListTitle } from "../parts/";

interface Props {
  title?: string;
  image?: string;
  onClicked?: () => void;
  children?: React.ReactNode;
}
export const ListItemGroup = (props: Props) => {
  const { title, image, onClicked, children } = props;
  const hasBottomMargin = { bottom: true };
  return (
    <div onClick={onClicked}>
      <Layout hasMargin={hasBottomMargin}>
        <ListThumbnailImage image={image} />
      </Layout>
      <Layout hasMargin={hasBottomMargin}>
        <ListTitle title={title} />
      </Layout>

      <>{children}</>
    </div>
  );
};
