// examples/destination/vue/src/components/screens/DestinationRegistrationScreen.vue
<template>
    <ScreenWrapper pageTitle="宛先登録">
        <DestinationEditContainer />
    </ScreenWrapper>
</template>

<script>
/**
 * 宛先登録画面
 * DestinationRegistration Screen
 */

// Components
import { DestinationEditContainer } from "@/components/containers"
import { ScreenWrapper } from "@/components/gui/parts"

export default {
    name: "DestinationRegistrationScreen",
    components: {
        DestinationEditContainer,
        ScreenWrapper
    }
}
</script>

// examples/destination/react/src/components/screens/DestinationRegistrationScreen.tsx
/**
 * 宛先登録画面
 * DestinationRegistration Screen
 */
import React from "react";

// Components
import { DestinationEditContainer } from "../containers";
import { ScreenWrapper } from "../gui/parts";

export const DestinationRegistrationScreen = () => (
  <ScreenWrapper pageTitle="宛先登録">
    <DestinationEditContainer />
  </ScreenWrapper>
);
