// examples/destination/react/src/components/gui/parts/TextField.tsx
/**
 * テキストフィールド
 * TextField GUI Component
 * @defaultValue 初期に表示する値
 * @placeholder プレイスホルダーに表示するテキスト
 * @onChanged 入力変更時のイベント
 */
import React from "react";
import styled from "styled-components";

interface Props {
  defaultValue?: string;
  placeholder?: string;
  onChanged?: (res: React.BaseSyntheticEvent) => void;
}

export const TextField = (props: Props) => {
  const { defaultValue, placeholder, onChanged } = props;

  return (
    <StyledFiled
      placeholder={placeholder || "入力してください…"}
      defaultValue={defaultValue}
      onChange={onChanged}
    />
  );
};

// input要素をTextFiled用のスタイルとしてラップ
const StyledFiled = styled.input`
  border: 1px solid #676767;
  border-radius: 6px;
  font-size: 1.4em;
  outline: none;
  padding: 10px 8px 8px;
`;

// examples/destination/vue/src/components/gui/parts/TextField.vue
<template>
    <StyledFiled
      :placeholder="placeholder || '入力してください…'"
      :value="text"
      @input="onInputed"
    />
</template>

<script>
//@input="onInputed"
/**
 * テキストフィールド
 * TextField GUI Component
 * @defaultValue 初期に表示する値
 * @placeholder プレイスホルダーに表示するテキスト
 * @onChanged 入力変更時のイベント
 */
import styled from "vue-styled-components";

// input要素をTextFiled用のスタイルとしてラップ
const StyledFiled = styled.input`
  border: 1px solid #676767;
  border-radius: 6px;
  font-size: 1.4em;
  outline: none;
  padding: 10px 8px 8px;
`;

export default {
    name: "TextField",
    data() {
      return {
        text: ""
      }
    },
    props: {
        defaultValue: String,
        placeholder: String,
        onChanged: Function
    },
    components: {
        StyledFiled
    },
    created() {
      this.text = this.defaultValue;
    },
    methods: {
      onInputed(res) {
        if(!this.onChanged) return;
        
        const value = res.target.value;
        this.onChanged(value);
      }
    }
}
</script>
