// examples/destination/react/src/components/screens/DestinationScreen.tsx
/**
 * 宛先画面
 * DestinationRegistration Screen
 */
import React from "react";

// Components
import { DestinationContainer } from "../containers";
import { ScreenWrapper } from "../gui/parts";

export const DestinationScreen = () => (
  <ScreenWrapper pageTitle="宛先">
    <DestinationContainer />
  </ScreenWrapper>
);

// examples/destination/vue/src/components/screens/DestinationScreen.vue
<template>
    <ScreenWrapper pageTitle="宛先">
        <DestinationContainer />
    </ScreenWrapper>
</template>

<script>
/**
 * 宛先画面
 * Destination Screen
 */

// Components
import { DestinationContainer } from "@/components/containers"
import { ScreenWrapper } from "@/components/gui/parts"

export default {
    name: "DestinationScreen",
    components: {
        DestinationContainer,
        ScreenWrapper
    }
}
</script>
