// examples/aparel-ec/react/src/components/gui/parts_/ListThumbnailImage.tsx
/**
 * ListThumbnailImage
 * @imageURL
 */
import React from "react";
import styled from "styled-components";

// Constants
const THUMBS_IMAGE_SIZE = 160;

interface Props {
  image?: string;
}
export const ListThumbnailImage = (props: Props) => {
  const { image } = props;
  const HasImage = () =>
    image ? <StyledImage src={image} /> : <StyledNoneImage />;
  return <>{HasImage()}</>;
};

const widthHeight = `
  width: ${THUMBS_IMAGE_SIZE}px;
  height: ${THUMBS_IMAGE_SIZE}px;
`;
const StyledImage = styled.img`
  ${widthHeight}
  border-radius: 6px;
`;
const StyledNoneImage = styled.div`
  ${widthHeight}
  background-color: #000;
  border-radius: 6px;
`;

// examples/aparel-ec/vue/src/components/gui/parts/ListThumbnailImage.vue
<template>
  <styled-image v-if="image" :src="image" />
  <styled-none-image v-else />
</template>

<script>
/**
 * ListThumbnailImage
 * @image 画像のURL
 */
import styled from "vue-styled-components";
import { THUMBS_IMAGE_SIZE } from "@/constants";

const widthHeight = `
  width: ${THUMBS_IMAGE_SIZE}px;
  height: ${THUMBS_IMAGE_SIZE}px;
`;
const StyledImage = styled.img`
  ${widthHeight}
  border-radius: 6px;
`;
const StyledNoneImage = styled.div`
  ${widthHeight}
  background-color: #000;
  border-radius: 6px;
`;

export default {
  name: "ListThumbnailImage",
  props: {
    image: String
  },
  components: {
    StyledImage,
    StyledNoneImage
  }
}
</script>
