// examples/destination/vue/src/components/gui/parts/FieldBlockWrapper.vue
<template>
    <StyledWrapper v-if="heading">
      <StyledHeading>{{heading}}</StyledHeading>
      <div><slot /></div>
    </StyledWrapper>
</template>

<script>
/**
 * 見出し付きのフィールドブロック
 * FieldBlockWrapper GUI Parts Component
 */
import styled from "vue-styled-components"

const StyledWrapper = styled.section``;
const StyledHeading = styled.h1``;

export default {
    name: "FieldBlockWrapper",
    props: {
        heading: String
    },
    components: {
        StyledWrapper,
        StyledHeading
    }
}
</script>

// examples/destination/react/src/components/gui/parts/FieldBlockWrapper.tsx
/**
 * 見出し付きのフィールドブロック
 * FieldBlockWrapper GUI Parts Component
 */
import React from "react";
import styled from "styled-components";

interface Props {
  children: React.ReactNode;
  heading?: string;
}
export const FieldBlockWrapper = (props: Props) => {
  const { heading, children } = props;
  if (!heading) return <></>;

  return (
    <StyledWrapper>
      <StyledHeading>{heading}</StyledHeading>
      <div>{children}</div>
    </StyledWrapper>
  );
};

const StyledWrapper = styled.section``;
const StyledHeading = styled.h1``;
