// examples/destination/react/src/components/layouts/LayoutFlex.tsx
/**
 * Flexレイアウト用
 * LayoutFlex Component
 * ※誌面上ではStyledComponentを使用していませんが、このコード上では採用しています。
 */
import React from "react";
import styled from "styled-components";
import {
  FlexDirectionProperty,
  TextJustifyProperty,
  BoxAlignProperty
} from "csstype";

interface StyledProps {
  height?: String | number;
  direction?: FlexDirectionProperty;
  justify?: TextJustifyProperty;
  verticalAlign?: BoxAlignProperty;
}
interface Props extends StyledProps {
  children: React.ReactNode;
}

export const LayoutFlex = (props: Props) => {
  const { direction, justify, verticalAlign, height, children } = props;
  return (
    <StyledFlexBox {...{ direction, justify, verticalAlign, height }}>
      {children}
    </StyledFlexBox>
  );
};

const StyledFlexBox = styled.div`
  display: flex;
  flex-direction: ${(props: StyledProps) => props.direction || "row"};
  justify-content: ${(props: StyledProps) => props.justify || "space-between"};
  align-items: ${(props: StyledProps) => props.verticalAlign || "center"};

  ${(props: StyledProps) => {
    if (!props.height) return;
    return `height: ${props.height}`;
  }}
`;

// examples/destination/vue/src/components/layouts/LayoutFlex.vue
<template>
    <StyledFlexBox 
        :direction="direction" 
        :justify="justify" 
        :vertical-align="verticalAlign" 
        :height="height">
        <slot />
    </StyledFlexBox>
</template>

<script>
/**
 * Flexレイアウト用
 * LayoutFlex Component
 * @slot ラップする中身
 */
import styled from "vue-styled-components";

const StyledFlexBoxProps = {
    direction: String, 
    justify: String, 
    verticalAlign: String, 
    height: [String, Number]
}
const StyledFlexBox = styled("div", StyledFlexBoxProps)`
  display: flex;
  flex-direction: ${(props) => props.direction || "row"};
  justify-content: ${(props) => props.justify || "space-between"};
  align-items: ${(props) => props.verticalAlign || "center"};

  ${(props) => {
    if (!props.height) return;
    return `height: ${props.height}`;
  }}
`;

export default {
    name: "LayoutFlex",
    props: StyledFlexBoxProps,
    components: {
        StyledFlexBox,
    }
}
</script>
