// examples/destination/vue/src/components/layouts/Layout.vue
<template>
    <StyledWrapper :hasPadding="hasPadding" :hasMargin="hasMargin">
      <slot />
    </StyledWrapper>
</template>

<script>
/**
 * レイアウトの子要素用
 * Layout Component
 * @hasPadding paddingの有無[left<Boolean>,top<Boolean>,right<Boolean>,bttom<Boolean>]
 * @hasMargin marginの有無[left<Boolean>,top<Boolean>,right<Boolean>,bttom<Boolean>]
 * @slot ラップする中身
 */
import styled from "vue-styled-components";

const StyledWrapperProps = {
    hasPadding: {
        left: Boolean,
        top: Boolean,
        right: Boolean,
        bottom: Boolean
    }, 
    hasMargin: {
        left: Boolean,
        top: Boolean,
        right: Boolean,
        bottom: Boolean
    }
}

const StyledWrapper = styled("div", StyledWrapperProps)`
  ${props => {
    const hasMargin = props.hasMargin || {};
    const hasPadding = props.hasPadding || {};
    const getSpace = bool => (bool ? `36px` : 0);

    return `
      margin-bottom: ${getSpace(
        typeof hasMargin.bottom === "boolean" ? hasMargin.bottom : true
      )};
      margin-top: ${getSpace(hasMargin.top)};
      margin-right: ${getSpace(hasMargin.right)};
      margin-left: ${getSpace(hasMargin.left)};

      padding-bottom: ${getSpace(hasPadding.bottom)};
      padding-top: ${getSpace(hasPadding.top)};
      padding-right: ${getSpace(hasPadding.right)};
      padding-left: ${getSpace(hasPadding.left)};
    `;
  }};
`;


export default {
    name: "Layout",
    props: StyledWrapperProps,
    components: {
        StyledWrapper
    }
}
</script>

// examples/aparel-ec/react/src/components/layouts/Layout.tsx
/**
 * ブロックレイアウト用（Margin, Padding）
 * BlockLayout Component
 * @hasMargin marginの有無[left,top,right,bttom]
 * @hasPadding paddingの有無[left,top,right,bttom]
 * @children ラップする中身
 */
import React from "react";
import styled from "styled-components";

interface LeftTopRightBottom {
  left?: boolean;
  top?: boolean;
  right?: boolean;
  bottom?: boolean;
}
interface StyledProps {
  hasPadding?: LeftTopRightBottom;
  hasMargin?: LeftTopRightBottom;
}
interface Props extends StyledProps {
  children: React.ReactNode;
}

export const Layout = (props: Props) => {
  const { children, hasPadding, hasMargin } = props;
  return (
    <StyledWrapper hasPadding={hasPadding} hasMargin={hasMargin}>
      {children}
    </StyledWrapper>
  );
};

const StyledWrapper = styled.div`
  ${(props: StyledProps) => {
    const hasMargin = props.hasMargin || {};
    const hasPadding = props.hasPadding || {};
    const getSpace = (bool?: boolean) => (bool ? `36px` : 0);

    return `
      margin-bottom: ${getSpace(
        typeof hasMargin.bottom === "boolean" ? hasMargin.bottom : true
      )};
      margin-top: ${getSpace(hasMargin.top)};
      margin-right: ${getSpace(hasMargin.right)};
      margin-left: ${getSpace(hasMargin.left)};

      padding-bottom: ${getSpace(hasPadding.bottom)};
      padding-top: ${getSpace(hasPadding.top)};
      padding-right: ${getSpace(hasPadding.right)};
      padding-left: ${getSpace(hasPadding.left)};
    `;
  }};
`;
