// examples/aparel-ec/vue/src/components/containers/BrandCollectionContainer.vue
<script>
/**
 * BrandCollectionContainer
 * ブランド（一覧）のコンテナ
 */
import { connect } from "vuex-connect";

// Components
import { Brands } from "@/components/domain/objects/";

export default connect({
    stateToProps:  {
        brands: state => state.brands
    }
})("BrandCollectionContainer", Brands)
</script>

// examples/aparel-ec/react/src/components/containers/BrandCollectionContainer.tsx
/**
 * ブランド一覧のコンテナ
 * BrandCollectionContainer Component
 */
import React from "react";
import { useSelector } from "react-redux";

// Components
import { Brands } from "../domain/objects";

// Redux
import { brandsSelector } from "../../redux/selectors";

export const BrandCollectionContainer = () => {
  const brands = useSelector(brandsSelector);

  return (
    <>
      <h1>ブランド</h1>
      <Brands brands={brands} />
    </>
  );
};
