// examples/aparel-ec/vue/src/components/containers/ProductCollectionContainer.vue
<script>
/**
 * ProductCollectionContainer
 * 商品（一覧）のコンテナ
 */
import store from "@/vuex/store";
import { connect } from "vuex-connect";

// Components
import { Products } from "@/components/domain/objects/";

export default connect({
    stateToProps:  {
        products: ()=> store.getters.productList
    }
})("ProductCollectionContainer", Products)
</script>

// examples/aparel-ec/react/src/components/containers/ProductCollectionContainer.tsx
/**
 * 商品コレクションのコンテナ
 * ProductCollectionContainer
 */
import React from "react";
import { useSelector } from "react-redux";

// Redux
import { productsSelector } from "../../redux/selectors";

// Components
import { Products } from "../domain/objects";

export const ProductCollectionContainer = () => {
  const products = useSelector(productsSelector);

  return <Products products={products} />;
};
