// examples/destination/vue/src/components/layouts/LayoutFlexItem.vue
<template>
    <styled-flex :column="column">
        <slot />
    </styled-flex>
</template>

<script>
/**
 * Flexレイアウトの子要素用
 * LayoutFlexItem Component
 * @column カラムの数
 * @slot ラップする中身
 */
import styled from "vue-styled-components";

const StyleFlexProps = {column: [Number, String]}
const StyledFlex = styled('div', StyleFlexProps)`
    
  ${props => {
    if (!props.column) return;
    return `flex: ${props.column}`;
  }}
`;


export default {
    name: "LayoutFlexItem",
    props: StyleFlexProps,
    components: {
        StyledFlex
    }
}
</script>

// examples/destination/react/src/components/layouts/LayoutFlexItem.tsx
/**
 * Flexレイアウトの子要素用
 * LayoutFlexItem Component
 * @column カラムの数
 * @children ラップする中身
 */

import React from "react";
import styled from "styled-components";

interface StyledProps {
  column?: number | string;
}
interface Props extends StyledProps {
  children: React.ReactNode;
}
export const LayoutFlexItem = (props: Props) => (
  <StyledFlex column={props.column}>{props.children}</StyledFlex>
);

const StyledFlex = styled.div`
  ${(props: StyledProps) => {
    if (!props.column) return;
    return `flex: ${props.column}`;
  }}
`;
