// examples/aparel-ec/vue/src/components/domain/objects/Brands.vue
<template>
  <layout-list>
    <layout-list-item v-for="(brand, key, index) in brands" :key="index">
      <brand-list-item 
        :logo="brand.logoImage" 
        :id="brand.id" 
        :name="brand.name" 
        :label="brand.label" />
    </layout-list-item>
  </layout-list>
</template>

<script>
/**
 * ブランド一覧
 * Brands Domain Object
 * @brands ブランド
 */

// Components
import { LayoutList, LayoutListItem } from "@/components/layouts";
import { BrandListItem } from "@/components/domain/elements";

export default {
  name: "Brands",
  props: {
    brands: Array
  },
  components: {
    LayoutList, 
    LayoutListItem,
    BrandListItem
  }
}
</script>

// examples/aparel-ec/react/src/components/domain/objects/Brands.tsx
/**
 * ブランド一覧
 * Brands Domain Object
 * @brands ブランド
 */
import React from "react";

// Components
import { LayoutList, LayoutListItem } from "../../layouts";
import { BrandListItem } from "../elements";

// Types
import { typeBrands, typeBrand } from "aparel-ec";

interface Props {
  brands?: typeBrands;
}
export const Brands = (props: Props) => {
  const { brands } = props;

  const BrandList = () => {
    if (!brands) return;

    return brands.map((brand: typeBrand, index: number) => {
      const { id, name, label, logoImage } = brand;

      return (
        <LayoutListItem key={index}>
          <BrandListItem logo={logoImage} {...{ id, name, label }} />
        </LayoutListItem>
      );
    });
  };

  return (
    <LayoutList>{BrandList() || "ブランドが登録されていません。"}</LayoutList>
  );
};
