// examples/aparel-ec/vue/src/components/domain/objects/Categories.vue
<template>
  <layout-line-list>
    <layout-line-list-item v-for="(category, key, index) in categories" :key="index">
      <category-list-item 
        :name="category.name"
        :label="category.label" />
    </layout-line-list-item>
  </layout-line-list>
</template>

<script>
/**
 * カテゴリ一覧
 * Categories Domain Object
 * @categories カテゴリ
 */

// Components
import { LayoutLineList, LayoutLineListItem } from "@/components/layouts";
import { CategoryListItem } from "@/components/domain/elements";

export default {
  name: "Categories",
  props: {
    categories: Array
  },
  components: {
    LayoutLineList, 
    LayoutLineListItem,
    CategoryListItem
  }
}
</script>

// examples/aparel-ec/react/src/components/domain/objects/Categories.tsx
/**
 * カテゴリ一覧
 * Categories Domain Object
 * @categories カテゴリ
 */
import React from "react";

// Components
import { LayoutLineList, LayoutLineListItem } from "../../layouts";
import { CategoryListItem } from "../elements";

// Types
import { typeCategories, typeCategory } from "aparel-ec";

interface Props {
  categories?: typeCategories;
}
export const Categories = (props: Props) => {
  const { categories } = props;

  const CategoryList = () => {
    if (!categories) return;

    return categories.map((category: typeCategory, index: number) => {
      const { name, label } = category; //, childCategories

      return (
        <LayoutLineListItem key={index}>
          <CategoryListItem {...{ name, label }} />
        </LayoutLineListItem>
      );
    });
  };

  return (
    <LayoutLineList>
      {CategoryList() || "カテゴリが登録されていません。"}
    </LayoutLineList>
  );
};
