// examples/aparel-ec/vue/src/components/domain/objects/Products.vue
<template>
  <layout-list v-if="hasProduct">
    <layout-list-item v-for="(product, key, index) in products" :key="index">
      <product-list-item 
        :title="product.title" 
        :brand-name="product.brand? product.brand.name : undefined" 
        :price-label="product.priceLabel" 
        :thumbnail="product.thumbnail" />
    </layout-list-item>
  </layout-list>
  
  <not-found-message v-else />
</template>

<script>
/**
 * 商品一覧
 * Products Domain Object
 * @products 商品
 */

// Components
import { LayoutList, LayoutListItem } from "@/components/layouts";
import { ProductListItem } from "@/components/domain/elements";
import { NotFoundMessage } from "@/components/gui/parts";


export default {
  name: "Products",
  props: {
    products: Array
  },
  computed: {
    hasProduct() {
      if(!this.products) return false;
      return this.products.length > 0
    }
  },
  components: {
    LayoutList, 
    LayoutListItem,
    ProductListItem,
    NotFoundMessage
  }
}
</script>

// examples/aparel-ec/react/src/components/domain/objects/Products.tsx
/**
 * 商品一覧
 * Products Domain Object
 * @products 商品
 */
import React from "react";

// Components
import { LayoutList, LayoutListItem } from "../../layouts";
import { ProductListItem } from "../elements";
import { NotFoundMessage } from "../../gui/parts";

// Types
import { typeProductList, typeProductListItem } from "aparel-ec";

interface Props {
  products: typeProductList;
}
export const Products = (props: Props) => {
  const { products } = props;

  const ProductListItems = products.map(
    (product: typeProductListItem, index: number) => {
      const { title, brandName, priceLabel, thumbnail } = product;

      return (
        <LayoutListItem key={index}>
          <ProductListItem {...{ title, brandName, priceLabel, thumbnail }} />
        </LayoutListItem>
      );
    }
  );

  const ProductList = () => {
    if (products.length === 0) return;
    return <LayoutList>{ProductListItems}</LayoutList>;
  };

  const ProductNone = () => {
    if (products.length > 0) return;
    return <NotFoundMessage />;
  };

  return (
    <LayoutList>
      <>{ProductList()}</>
      <>{ProductNone()}</>
    </LayoutList>
  );
};
