// examples/aparel-ec/vue/src/components/screens/BrandsScreen.vue
<template>
  <screen-wrapper pageTitle="ブランド">
    <brand-collection-container />
  </screen-wrapper>
</template>

<script>
/**
 * ブランド画面
 * Brand Screen Component
 */
//Components
import { BrandCollectionContainer } from "@/components/containers";
import { ScreenWrapper } from "@/components/gui/parts";

export default {
    name: "BrandScreen",
    components: {
      BrandCollectionContainer,
      ScreenWrapper
    }
}
</script>

// examples/aparel-ec/react/src/components/screens/BrandsScreen.tsx
/**
 * ブランド一覧画面
 * Brands Screen
 */
import React from "react";

// Components
import { BrandCollectionContainer } from "../containers";
import { ScreenWrapper } from "../gui/parts";

export const BrandsScreen = () => {
  return (
    <ScreenWrapper>
      <h1>ブランド一覧</h1>
      <BrandCollectionContainer />
    </ScreenWrapper>
  );
};
