// examples/aparel-ec/vue/src/components/screens/BrandDetailScreen.vue
<template>
  <screen-wrapper pageTitle="ブランド">
    <select-brand-container />
    <product-collection-by-brand-container />
  </screen-wrapper>
</template>

<script>
/**
 * 任意ブランドの詳細画面
 * BrandDetail Screen Component
 */
import store from "@/vuex/store";
import MUTATIONTYPE from "@/vuex/mutaitonTypes";

//Components
import { SelectBrandContainer, ProductCollectionByBrandContainer } from "@/components/containers";
import { ScreenWrapper } from "@/components/gui/parts";

export default {
    name: "BrandDetailScreen",
    props:{
      label: String
    },
    components: {
      SelectBrandContainer, 
      ProductCollectionByBrandContainer,
      ScreenWrapper
    },
    created() {
      store.commit(MUTATIONTYPE.SELECT_BRAND, this.label)
    }
}
</script>

// examples/aparel-ec/react/src/components/screens/BrandDetailScreen.tsx
/**
 * ブランド詳細画面
 * BrandDetail Screen
 */
import React from "react";

// Components
import { ProductCollectionByBrandContainer } from "../containers";
import { ScreenWrapper } from "../gui/parts";

export const BrandDetailScreen = (props: any) => {
  const label = props.match.params.label;

  return (
    <ScreenWrapper>
      <h1>カテゴリ詳細</h1>
      <ProductCollectionByBrandContainer label={label} />
    </ScreenWrapper>
  );
};
