// examples/aparel-ec/vue/src/components/screens/CategoryDetailScreen.vue
<template>
  <screen-wrapper pageTitle="カテゴリ">
    <select-category-container />
    <product-collection-by-category-container />
  </screen-wrapper>
</template>

<script>
/**
 * 任意カテゴリの詳細画面
 * CategoryDetail Screen Component
 */
import store from "@/vuex/store";
import MUTATIONTYPE from "@/vuex/mutaitonTypes";

//Components
import { SelectCategoryContainer, ProductCollectionByCategoryContainer } from "@/components/containers";
import { ScreenWrapper } from "@/components/gui/parts";

export default {
    name: "CategoryDetailScreen",
    props:{
      label: String
    },
    components: {
      SelectCategoryContainer, 
      ProductCollectionByCategoryContainer,
      ScreenWrapper
    },
    created() {
      store.commit(MUTATIONTYPE.SELECT_CATEGORY, this.label)
    }
}
</script>

// examples/aparel-ec/react/src/components/screens/CategoryDetailScreen.tsx
/**
 * カテゴリ詳細画面
 * CategoryDetail Screen
 */
import React from "react";

// Components
import { ProductCollectionByCategoryContainer } from "../containers";
import { ScreenWrapper } from "../gui/parts";

export const CategoryDetailScreen = (props: any) => {
  const label = props.match.params.label;

  return (
    <ScreenWrapper>
      <h1>カテゴリ詳細</h1>
      <ProductCollectionByCategoryContainer label={label} />
    </ScreenWrapper>
  );
};
