// examples/aparel-ec/vue/src/components/screens/CategoriesScreen.vue
<template>
  <screen-wrapper pageTitle="カテゴリ">
    <category-collection-container />
  </screen-wrapper>
</template>

<script>
/**
 * カテゴリ画面
 * Categories Screen Component
 */
//Components
import { CategoryCollectionContainer } from "@/components/containers";
import { ScreenWrapper } from "@/components/gui/parts";

export default {
    name: "CategoriesScreen",
    components: {
      CategoryCollectionContainer,
      ScreenWrapper
    }
}
</script>

// examples/aparel-ec/react/src/components/screens/CategoriesScreen.tsx
/**
 * カテゴリ一覧画面
 * Categories Screen
 */
import React from "react";

// Components
import { CategoriesContainer } from "../containers";
import { ScreenWrapper } from "../gui/parts";

export const CategoriesScreen = () => {
  return (
    <ScreenWrapper>
      <h1>カテゴリ一覧</h1>
      <CategoriesContainer />
    </ScreenWrapper>
  );
};
