// examples/destination/vue/src/components/domain/objects/Dashboard.vue
<template>
    <div>
        <Heading text="宛先" />
        <ul>
            <li>
                <router-link to="/reference">確認</router-link>
            </li>
            <li>
                <router-link to="/registration">登録</router-link>
            </li>
        </ul>
    </div>
</template>

<script>
/**
 * ダッシュボード
 * Dashboard Domain Object Component
 */

// Components
import { Heading } from "@/components/gui/parts";

export default {
    name: 'Dashboard',
    components: {
        Heading
    }
}
</script>

// examples/destination/react/src/components/domain/objects/Dashboard.tsx
/**
 * ダッシュボード
 * Dashboard Domain Object Component
 */
import React from "react";
import { Link } from "react-router-dom";

// Components
import { Heading } from "../../gui/parts";

export const Dashboard = () => (
  <>
    <Heading text="宛先" />
    <ul>
      <li>
        <Link to="/reference">確認</Link>
      </li>
      <li>
        <Link to="/registration">登録</Link>
      </li>
    </ul>
  </>
);
