// examples/destination/vue/src/components/domain/objects/DestinationEdit.vue
<template>
    <div>
        <Layout>
            <NameEdit 
                :on-changed="name.onChanged" 
                :first-name="name.firstName" 
                :last-name="name.lastName" />
        </Layout>
        <Layout>
            <PostalCodeEdit
                :onChanged="postalCode.onChanged"
                :upper="postalCode.upper"
                :lower="postalCode.lower"
            />
        </Layout>
        <Layout>
            <AddressEdit
                :on-selected-prefecture="address.onSelectedPrefecture"
                :on-city-street-changed="address.onCityStreetChanged"
                :prefecture="address.prefecture"
                :city-street="address.cityStreet"
            />
        </Layout>
        <Layout>
            <RegistrationButton :on-registed="onRegisted" />
        </Layout>
        <LayoutSpacer :height="'40px'" />
    </div>
</template>

<script>
/**
 * 宛先登録
 * Destination Edit Domain Object Component
 * @name 宛先の名前
 * @postalCode 郵便番号
 * @address 住所
 * @onRegisted 宛先登録時のイベント
 */

// Components
import { 
    AddressEdit, 
    NameEdit, 
    PostalCodeEdit, 
    RegistrationButton 
} from "@/components/domain/elements";
import { Layout, LayoutSpacer } from "@/components/layouts";

export default {
    name: "DestinationEdit",
    props: {
        name: {
            firstName: String,
            lastName: String,
            onChanged: Function
        },
        postalCode: {
            upper: String,
            lower: String,
            onChanged: Function
        },
        address: {
            prefecture: String,
            cityStreet: String,
            onCityStreetChanged: Function,
            onSelectedPrefecture: Function
        },
        onRegisted: Function
    },
    components: {
        AddressEdit, 
        NameEdit, 
        PostalCodeEdit,
        RegistrationButton,
        Layout,
        LayoutSpacer
    }
}
</script>

// examples/destination/react/src/components/domain/objects/DestinationEdit.tsx
/**
 * 宛先登録
 * Destination Edit Domain Object Component
 * @name 宛先の名前
 * @postalCode 郵便番号
 * @address 住所
 */
import React from "react";

// Components
import {
  AddressEdit,
  NameEdit,
  PostalCodeEdit,
  RegistrationButton
} from "../elements";
import { Layout, LayoutSpacer } from "../../layouts";

// Types
import {
  typeName,
  typeNameEvent,
  typePostalCode,
  typePostalCodeEvent,
  typeCityStreet,
  typeCityStreetEvent,
  typePrefecture,
  typePrefectureEvent
} from "destination";

interface Props {
  name: {
    firstName?: typeName["firstName"];
    lastName?: typeName["lastName"];
    onChanged?: typeNameEvent;
  };
  postalCode: {
    upper?: typePostalCode["upper"];
    lower?: typePostalCode["lower"];
    onChanged?: typePostalCodeEvent;
  };
  address: {
    prefecture?: typePrefecture;
    cityStreet?: typeCityStreet;
    onCityStreetChanged: typeCityStreetEvent;
    onSelectedPrefecture: typePrefectureEvent;
  };
  onRegisted?: () => void;
}

export const DestinationEdit = (props: Props) => {
  const { name, postalCode, address, onRegisted } = props;
  const { firstName, lastName } = name;
  const { upper, lower } = postalCode;
  const { prefecture, cityStreet } = address;

  return (
    <>
      <Layout>
        <NameEdit onChanged={name.onChanged} {...{ firstName, lastName }} />
      </Layout>
      <Layout>
        <PostalCodeEdit
          onChanged={postalCode.onChanged}
          {...{ upper, lower }}
        />
      </Layout>
      <Layout>
        <AddressEdit
          onSelectedPrefecture={address.onSelectedPrefecture}
          onCityStreetChanged={address.onCityStreetChanged}
          {...{ prefecture, cityStreet }}
        />
      </Layout>
      <Layout>
        <RegistrationButton onRegisted={onRegisted} />
      </Layout>
      <LayoutSpacer height="40px" />
    </>
  );
};
