// examples/aparel-ec/react/src/components/layouts/LayoutLineList.tsx
/**
 * ラインリスト用レイアウト
 * LineListLayout Component
 */
import React from "react";
import styled from "styled-components";

interface Props {
  children: React.ReactNode;
}
export const LayoutLineList = (props: Props) => {
  const { children } = props;
  return <StyledFlexUl>{children}</StyledFlexUl>;
};

const StyledFlexUl = styled.ul`
  margin: 0;
  padding: 0;
`;

// examples/aparel-ec/vue/src/components/layouts/LayoutLineList.vue
<template>
  <styled-flex-ul><slot /></styled-flex-ul>
</template>

<script>
/**
 * ラインリスト用レイアウト
 * LineListLayout Component
 */
import styled from "vue-styled-components";

const StyledFlexUl = styled.ul`
  margin: 0;
  padding: 0;
`;

export default {
  name: "LayoutLineList",
  components: {
    StyledFlexUl
  }
}
</script>
