// examples/aparel-ec/react/src/components/layouts/LayoutListItem.tsx
/**
 * リストアイテム用レイアウト
 * ListItemLayout Component
 * @column カラムの幅
 */
import React from "react";
import styled from "styled-components";

interface StyledProps {
  column?: number | string;
}
interface Props extends StyledProps {
  children: React.ReactNode;
}
export const LayoutListItem = (props: Props) => {
  const { column, children } = props;
  return <StyledListItem column={column}>{children}</StyledListItem>;
};

const StyledListItem = styled.li`
  list-style-type: none;
  text-align: center;
  border-bottom: 1px dashed rgba(0, 0, 0, 0.5);
  padding-top: 16px;
  flex: 170px;
  max-width: 50%;

  ${(props: StyledProps) => {
    if (!props.column) return;
    return `flex: ${props.column}`;
  }};
`;

// examples/aparel-ec/vue/src/components/layouts/LayoutListItem.vue
<template>
  <styled-list-item :column="column"><slot /></styled-list-item>
</template>

<script>
/**
 * リストアイテム用レイアウト
 * ListItemLayout Component
 * @column カラムの幅
 */
import styled from "vue-styled-components";

const StyledProps = {
  column: [Number, String]
}
const StyledListItem = styled('li', StyledProps)`
  list-style-type: none;
  text-align: center;
  border-bottom: 1px dashed rgba(0, 0, 0, 0.5);
  padding-top: 16px;
  flex: 170px;
  max-width: 50%;

  ${(props) => {
    if (!props.column) return;
    return `flex: ${props.column}`;
  }}
`;

export default {
  name: "LayoutListItem",
  props: StyledProps,
  components: {
    StyledListItem
  }
}
</script>
