// examples/destination/react/src/components/domain/objects/Destination.tsx
/**
 * 宛先参照（表示）
 * Destination Domain Object Component
 * @name 宛先の名前
 * @postalCode 郵便番号
 * @address 住所
 */

import React from "react";

// Components
import { Address, Name, PostalCode } from "../elements";
import { Layout } from "../../layouts";

// Types
import { typeFullName, typePostalCodeAll, typeAddress } from "destination";

interface Props {
  name?: typeFullName;
  postalCode?: typePostalCodeAll;
  address?: typeAddress;
}

export const Destination = (props: Props) => {
  const { name, postalCode, address } = props;

  return (
    <>
      <Layout>
        <Name fullName={name} />
      </Layout>

      <Layout>
        <PostalCode code={postalCode} />
      </Layout>

      <Layout>
        <Address address={address} />
      </Layout>
    </>
  );
};

// examples/destination/vue/src/components/domain/objects/Destination.vue
<template>
    <div>
        <Layout>
            <Name :full-name="name" />
        </Layout>

        <Layout>
            <PostalCode :code="postalCode" />
        </Layout>

        <Layout>
            <Address :address="address" />
        </Layout>
    </div>
</template>

<script>
/**
 * 宛先参照（表示）
 * Destination Domain Object Component
 * @name 宛先の名前
 * @postalCode 郵便番号
 * @address 住所
 */

// Components
import { Address, Name, PostalCode } from "@/components/domain/elements";
import { Layout } from "@/components/layouts";


export default {
    name: "Destination",
    props: {
        name: String,
        postalCode: String,
        address: String
    },
    components: {
        Address, 
        Name, 
        PostalCode, 
        Layout 
    }
}
</script>
