// examples/aparel-ec/vue/src/components/gui/parts/ListTitle.vue
<template>
  <StyledTitle>{{titleString}}</StyledTitle>
</template>

<script>
/**
 * リストタイトル
 * ListTitle GUI Parts
 * @title タイトル
 */
import styled from "vue-styled-components";

const StyledTitle = styled.strong`
  font-size: 1.6em;
  font-weight: bold;
`;

export default {
  name: "ListTitle",
  props: {
    title: String
  },
  computed: {
    titleString() {
      return this.title || "タイトル未設定"
    }
  },
  components: {
    StyledTitle
  }
}
</script>

// examples/aparel-ec/react/src/components/gui/parts/ListTitle.tsx
/**
 * リストタイトル
 * ListTitle GUI Parts
 * @title タイトル
 */
import React from "react";
import styled from "styled-components";

interface Props {
  title?: string;
}
export const ListTitle = (props: Props) => {
  const { title } = props;
  return <StyledTitle>{title || "タイトル未設定"}</StyledTitle>;
};

const StyledTitle = styled.strong`
  font-size: 1.6em;
  font-weight: bold;
`;
