// examples/aparel-ec/vue/src/components/gui/parts/NotFoundMessage.vue
<template>
  <styled-message>何もみつかりませんでした…</styled-message>
</template>

<script>
/**
 * NotfoundMessage GUI Parts Component
 */
import styled from "vue-styled-components";

const StyledMessage = styled.div`
  font-size: 1.6em;
  font-weight: bold;
  color: rgba(0, 0, 0, 0.5);
  text-align: center;
`;

export default {
  name: "NotFoundMessage",
  components: {
    StyledMessage
  }
}
</script>

// examples/aparel-ec/react/src/components/gui/parts/NotFoundMessage.tsx
/**
 * NotfoundMessage GUI Parts Component
 */
import React from "react";
import styled from "styled-components";

export const NotFoundMessage = () => {
  return <StyledMessage>何もみつかりませんでした…</StyledMessage>;
};

const StyledMessage = styled.div`
  font-size: 1.6em;
  font-weight: bold;
  color: rgba(0, 0, 0, 0.5);
  text-align: center;
`;
