// examples/aparel-ec/react/src/components/domain/elements/BrandListItem.tsx
/**
 * ブランド一覧のリストアイテム
 * BrandListItem Domain Element
 *
 * @name ブランド名
 * @logo ブランドロゴイメージ
 * @onRefered 任意ブランド参照する際のイベント
 */
import React from "react";
import useReactRouter from "use-react-router";
import styled from "styled-components";

// Components
import { ListItemGroup } from "../../gui/groups";
import { Layout } from "../../layouts";

// Constants
import { REFER_BRAND_LINK_LABEL } from "../../../constants";

// Types
import { typeBrand } from "aparel-ec";

interface Props {
  id?: typeBrand["id"];
  name?: typeBrand["name"];
  logo?: typeBrand["logoImage"];
  label?: typeBrand["label"];
}
export const BrandListItem = (props: Props) => {
  const { name, label, logo } = props;
  const hasMarginBottom = { bottom: true };
  const referLink = `/brand/${label}`;
  const { history } = useReactRouter();
  const onScreenTransition = () => history.push(referLink);

  return (
    <ListItemGroup title={name} image={logo} onClicked={onScreenTransition}>
      <Layout hasMargin={hasMarginBottom}>
        <StyledTransitionLabel>{REFER_BRAND_LINK_LABEL}</StyledTransitionLabel>
      </Layout>
    </ListItemGroup>
  );
};

const StyledTransitionLabel = styled.span`
  font-size: 0.8em;
`;

// examples/aparel-ec/vue/src/components/domain/elements/BrandListItem.vue
<template>
  <list-item-group :title="name" :image="logo" :onClicked="onScreenTransition">
      <layout :has-margin="hasMarginBottom">
        <styled-transition-label>{{REFER_BRAND_LINK_LABEL}}</styled-transition-label>
      </layout>
    </list-item-group>
</template>

<script>
/**
 * ブランド一覧のアイテム
 * BrandListItem GUI Parts Component
 * 
 */
import styled from "vue-styled-components";

// Contants
import CONSTANTS from "@/constants"

// Components
import { ListItemGroup } from "@/components/gui/groups";
import { Layout } from "@/components/layouts";

const StyledTransitionLabel = styled.span`
  font-size: 0.8em;
`;

export default {
  name: "BrandListItem",
  mixins: [CONSTANTS],
  props: {
    id: [String, Number],
    name: String,
    logo: String,
    label: String,
  },
  computed: {
    hasMarginBottom() { 
      return { bottom: true } 
    },
    referLink(){
      return `/brand/${this.label}`;
    } 
  },
  methods: {
    onScreenTransition() {
      location.href = this.referLink;
    }
  },
  components: {
    ListItemGroup,
    Layout,
    StyledTransitionLabel
  }
}
</script>
