// examples/aparel-ec/react/src/components/domain/elements/ProductListItem.tsx
/**
 * 商品一覧のリストアイテム
 * ProductListItem Domain Element
 *
 * @title 商品のタイトル
 * @thumbnail 商品のサムネイル画像
 * @priceLabel 商品のプライスラベル
 * @brandName 商品のブランド名
 * @onRefered 任意商品参照する際のイベント
 */
import React from "react";
import styled from "styled-components";

// Components
import { ListItemGroup } from "../../gui/groups";
import { Price } from "../../gui/parts";
import { Layout } from "../../layouts";

// Types
import {
  typeBrand,
  typeProduct,
  typeComputedPriceLabel,
  typeComputedProductTitle
} from "aparel-ec";

interface Props {
  brandName?: typeBrand["name"];
  priceLabel?: typeComputedPriceLabel;
  title?: typeComputedProductTitle;
  thumbnail?: typeProduct["thumbnailImage"];
}
export const ProductListItem = (props: Props) => {
  const { title, thumbnail, priceLabel, brandName } = props;
  const hasMarginBottom = { bottom: true };
  const noneMarginBottom = { bottom: true };

  return (
    <ListItemGroup title={title} image={thumbnail}>
      <Layout hasMargin={noneMarginBottom}>
        <Price value={priceLabel} />
      </Layout>
      <Layout hasMargin={hasMarginBottom}>
        <StyledBrandLabel>ブランド </StyledBrandLabel>
        <StyledBrandName>{brandName}</StyledBrandName>
      </Layout>
    </ListItemGroup>
  );
};

const StyledBrandLabel = styled.span`
  font-size: 0.8em;
  color: #666;
`;
const StyledBrandName = styled.strong`
  font-size: 1em;
  font-weight: bold;
`;

// examples/aparel-ec/vue/src/components/domain/elements/ProductListItem.vue
<template>
  <list-item-group :title="title" :image="thumbnail">
      <layout :has-margin="noneMarginBottom">
        <price :value="priceLabel" />
      </layout>
      <layout :hasMargin="hasMarginBottom">
        <styled-brand-label>ブランド </styled-brand-label>
        <styled-brand-name>{{brandName}}</styled-brand-name>
      </layout>
    </list-item-group>
</template>

<script>
/**
 * 商品一覧のアイテム
 * ProductListItem GUI Parts Component
 * @title リストのタイトル（商品名）
 * @thumbnail サムネイル（商品サムネイル画像）
 * @priceLabel 価格（商品の価格）
 * @brandName 商品のブランド
 */
import styled from "vue-styled-components";

// Components
import { ListItemGroup } from "@/components/gui/groups";
import { Price } from "@/components/gui/parts"
import { Layout } from "@/components/layouts";

const StyledBrandLabel = styled.span`
  font-size: 0.8em;
  color: #666;
`;
const StyledBrandName = styled.strong`
  font-size: 1em;
  font-weight: bold;
`;

export default {
  name: "ProductListItem",
  props: {
    title: String,
    thumbnail: String,
    priceLabel: String,
    brandName: String
  },
  computed: {
    hasMarginBottom() {
      return { bottom: true }
    },
    noneMarginBottom() {
      return { bottom: false }
    }
  },
  components: {
    StyledBrandLabel,
    StyledBrandName,
    ListItemGroup,
    Layout,
    Price
  }
}
</script>
