// examples/destination/react/src/components/domain/elements/RegistrationButton.tsx
/**
 * 登録ボタン
 * Resgistration Button
 * @onRegisted 登録する際のイベント
 */
import React from "react";

//Components
import { Button } from "../../gui/parts";

interface Props {
  onRegisted?: () => void;
}
export const RegistrationButton = (props: Props) => {
  const { onRegisted } = props;
  return <Button label="登録する" onPushed={onRegisted} />;
};

// examples/destination/vue/src/components/domain/elements/RegistrationButton.vue
<template>
    <Button :label="'登録する'" :on-pushed="onRegisted" />
</template>

<script>
/**
 * 登録ボタン
 * Resgistration Button
 * @onRegisted 登録する際のイベント
 */

//Components
import { Button } from "../../gui/parts";

export default {
    name: "RegistrationButton",
    props: {
        onRegisted: Function
    },
    components: {
        Button
    }
}
</script>
