// examples/aparel-ec/react/src/components/screens/ProductsScreen.tsx
/**
 * 商品一覧画面
 * Productions Screen
 */
import React from "react";

// Components
import { ProductCollectionContainer } from "../containers";
import { ScreenWrapper } from "../gui/parts";

export const ProductsScreen = () => {
  return (
    <ScreenWrapper>
      <h1>商品</h1>
      <ProductCollectionContainer />
    </ScreenWrapper>
  );
};

// examples/aparel-ec/vue/src/components/screens/ProductsScreen.vue
<template>
  <screen-wrapper pageTitle="商品">
    <product-collectionContainer />
  </screen-wrapper>
</template>

<script>
/**
 * 商品画面
 * Products Screen
 */
// Components
import { ProductCollectionContainer } from "@/components/containers";
import { ScreenWrapper } from "@/components/gui/parts";

export default {
    name: "ProductScreen",
    components: {
      ProductCollectionContainer,
      ScreenWrapper
    }
}
</script>
