// examples/aparel-ec/vue/src/components/gui/parts/ScreenWrapper.vue
<template>
  <styled-main>
      <layout
        :has-margin="layoutOption.MARGIN"
        :has-padding="layoutOption.PADDING"
      >
        <slot />
      </layout>
    </styled-main>
</template>

<script>
/**
 * ScreenWrapper GUI Parts Component
 */
import styled from "vue-styled-components";

// Components
import { Layout } from "@/components/layouts";

// Constants
const LAYOUT_OPTION = {
  MARGIN: {},
  PADDING: { left: true, right: true }
};

const StyledMain = styled.main`
  overflow: hidden;
  padding-top: 32px;
`;

export default {
  name: "ScreenWrapper",
  computed: {
    layoutOption() {
      return LAYOUT_OPTION
    }
  },
  components: {
    StyledMain,
    Layout
  }
}
</script>

// examples/aparel-ec/react/src/components/gui/parts_/ScreenWrapper.tsx
/**
 * ScreenWrapper GUI Parts Component
 */
import React from "react";
import styled from "styled-components";

// Components
import { Layout } from "../../layouts";

// Constants
const LAYOUT_OPTION = {
  MARGIN: {},
  PADDING: { left: true, right: true }
};

interface Props {
  children: React.ReactNode;
}

export const ScreenWrapper = (props: Props) => {
  const { children } = props;

  return (
    <StyledMain>
      <Layout
        hasMargin={LAYOUT_OPTION.MARGIN}
        hasPadding={LAYOUT_OPTION.PADDING}
      >
        {children}
      </Layout>
    </StyledMain>
  );
};

const StyledMain = styled.main`
  overflow: hidden;
  padding-top: 32px;
`;
