// examples/chapter2/react/src/components/OptionLabel.tsx
import React from "react";
import styled from "styled-components";

interface Props {
  text?: string;
  onClicked?: () => void;
}
export const OptionLabel = (props: Props) => {
  const { text, onClicked } = props;
  return <StyledLabel onClick={onClicked}>{text || "Label"}</StyledLabel>;
};

const StyledLabel = styled.label`
  position: relative;
  top: -7px;
  margin-left: 12px;
`;

// examples/chapter2/vue/src/components/OptionLabel.vue
<template>
    <styled-label v-on:click="onClicked">{{text}}</styled-label>
</template>

<script>
import styled from "vue-styled-components";

const StyledLabel = styled.label`
  position: relative;
  top: -7px;
  margin-left: 12px;
`;

export default {
    name: 'OptionLabel',
    props: {
      'text': String,
      'onClicked': Function
    },
    components: {
        StyledLabel
    }
}
</script>
